import { describe, expect, it } from 'vitest';
import { calculateFinancePlan, emiPaise, type FinanceInput } from './finance';
import vectors from './finance.vectors.json';

/**
 * The frontend live preview MUST match the authoritative server calculation.
 * `finance.vectors.json` is generated by the server
 * (`server/tests/helpers/gen-finance-vectors.ts`); if it changes, re-copy it.
 */
describe('frontend finance mirror matches the shared calculation contract', () => {
  for (const v of vectors as { name: string; input: FinanceInput; expected: Record<string, number> }[]) {
    it(v.name, () => {
      const plan = calculateFinancePlan(v.input);
      expect(plan.monthlyInstalmentPaise).toBe(v.expected.monthlyInstalmentPaise);
      expect(plan.finalInstalmentPaise).toBe(v.expected.finalInstalmentPaise);
      expect(plan.totalInterestPaise).toBe(v.expected.totalInterestPaise);
      expect(plan.totalRepaymentPaise).toBe(v.expected.totalRepaymentPaise);
      expect(plan.moratoriumInterestPaise).toBe(v.expected.moratoriumInterestPaise);
      expect(plan.repaymentMonths).toBe(v.expected.repaymentMonths);
      expect(plan.amortizationSchedule.at(-1)?.closingBalancePaise).toBe(0);
    });
  }

  it('zero-interest EMI is pure principal', () => {
    expect(emiPaise(120000, 0, 12)).toBe(10000);
  });
});
